####
#
# This config file imports all the other config files. They
# are split up based on what they config.
#
imports:
    - { resource: parameters.yml }
    - { resource: services.yml }
    - { resource: assetic.yml  }
    - { resource: doctrine.yml  }
    - { resource: framework.yml }
    - { resource: monolog.yml }
    - { resource: security.yml }
    - { resource: swiftmailer.yml }
    - { resource: twig.yml }
    - { resource: web_profiler.yml }

