####
#
# This config file will store sessions in a mysql database
# You will need to run the sql file found in the
# app/Resources/extras/sql directory
framework:
    session:
        handler_id: session.handler.pdo

parameters:
    pdo.db_options:
        db_table:     session
        db_id_col:    session_id
        db_data_col:  session_value
        db_time_col:  session_time

services:
    pdo:
        class: PDO
        arguments:
            dsn:       "mysql:host=%database_host%;dbname=%database_name%"
            user:      %database_user%
            password:  %database_password%

    session.handler.pdo:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionSessionHandler
        arguments: [@pdo, %pdo.db_options%]

