####
#
# Swiftmailer Configuration
#
# Reference: http://symfony.com/doc/current/reference/configuration/swiftmailer.html
#
swiftmailer:
    # smtp, gmail, mail, sendmail, null
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }
    logging:   "%kernel.debug%"

